name: '"Last successful commit" Github Action'
description: 'GitHub action for identifying the last successful commit for a given workflow and branch'
runs:
  using: node16
  main: "dist/index.js"
inputs:
  workflow-id:
    description: 'The workflow ID to check for the last successful commit. You can use the filename of the workflow'
    required: true
  branch:
    description: 'The branch to check for the last successful commit'
    required: false
  event:
    description: 'The event type to check for the last successful commit'
    required: false
  github-token:
    description: 'The GitHub token to use for the API calls'
    required: true
    default: ${{ github.token }}