name: Test the Action
on: [push, workflow_dispatch]

jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Minimal inputs test
    steps:
      # To use this repository's action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Action
        id: run-action
        uses: ./ # Uses an action in the root directory
        with:
          workflow-id: test-action.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Action Output
        run: echo Commit SHA is ${{ steps.run-action.outputs.commit-sha }}

  run_action_event:
    runs-on: ubuntu-latest
    name: With all filters test
    steps:
      # To use this repository's action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Action
        id: run-action
        uses: ./ # Uses an action in the root directory
        with:
          branch: main
          workflow-id: test-action.yml
          event: push
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Action Output
        run: echo Commit SHA is ${{ steps.run-action.outputs.commit-sha }}