name: Test the Action
on: [push, workflow_dispatch]

jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Run the action defined in this repository
    steps:
      # To use this repository's action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./ # Uses an action in the root directory
        with:
          branch: main
          workflow_id: test-action.yml
          event: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
